### ISSUE TITLE
Sleep for OS idle loop

### ISSUE THREAD

**Issue by nick-a-schneider** [JGoard/JOCKTOS#18]
```suggestion
WFI()
```
Simplest thing that we can do is just to include that into the scheduler. It will sleep until the next interrupt, and when no tasks are active. 

We could just try this for now since issues with memory retention and wakeup sources will be something we need to consider before diving deeper.

Some deeper sleep states will incur a small delay before becoming fully active again as clock sources re-stabilize, etc.

_Originally posted by @JGoard in https://github.com/JGoard/JOCKTOS/pull/8#discussion_r1702441060_

**Comment by JGoard** [comment]
When the PR is done this is closed @nick-a-schneider
